TAXONOMY = {
    "fields": {
        "Makine Mühendisliği": ["makine", "mekanik", "rulman", "titreşim", "pres", "kalıp", "cnc"],
        "Mekatronik ve Otomasyon": ["mekatronik", "otomasyon", "plc", "servo", "scada"],
        "Robotik": ["robot", "agv", "amr", "slam", "ros", "otonom"],
        "İmalat Mühendisliği": ["imalat", "sac", "kalıp", "pres", "talaşlı", "üretim prosesi"],
        "Bilgisayar ve Yapay Zekâ": ["yapay zeka", "makine öğrenmesi", "veri bilimi", "görüntü", "python"],
        "Elektrik-Elektronik Mühendisliği": ["elektrik", "elektronik", "motor sürücü", "bms", "devre"],
        "Enerji Sistemleri": ["enerji", "şebeke", "güneş", "rüzgar", "transformatör"],
        "Kimya Mühendisliği": ["kimya", "kimyasal", "reaksiyon", "polimer", "boya", "formülasyon"],
        "Çevre Mühendisliği": ["atık su", "atıksu", "arıtma", "membran", "emisyon"],
        "Malzeme ve Metalurji": ["malzeme", "metalurji", "korozyon", "aşınma", "ısıl işlem", "kompozit"],
        "Endüstri Mühendisliği": ["çizelgeleme", "tedarik", "lojistik", "hat dengeleme", "stok", "optimizasyon"],
        "Gıda Mühendisliği": ["gıda", "raf ömrü", "paket", "ambalaj", "pastörizasyon", "hijyen"],
        "Sürdürülebilirlik": ["karbon", "lca", "yaşam döngüsü", "sürdürülebilirlik", "emisyon"],
    },
    "skills": {
        "Titreşim Analizi": ["titreşim", "fft", "ivmeölçer", "frekans analizi"],
        "Kestirimci Bakım": ["kestirimci", "plansız duruş", "arıza tahmini", "bakım"],
        "PLC ve Otomasyon": ["plc", "scada", "otomasyon", "servo"],
        "Gömülü Sistemler ve IoT": ["stm32", "gömülü", "iot", "sensör", "mikrodenetleyici"],
        "Robotik ve Navigasyon": ["robot", "agv", "amr", "ros", "slam", "otonom"],
        "Sonlu Elemanlar Analizi": ["fea", "fem", "ansys", "abaqus", "sonlu eleman"],
        "Sac Şekillendirme": ["sac", "kalıp", "geri esneme", "springback", "pres"],
        "Bilgisayarlı Görü": ["kamera", "görüntü işleme", "computer vision", "yolo", "nesne tespiti"],
        "Zaman Serisi Analizi": ["zaman serisi", "tahmin", "sensör verisi", "trend"],
        "Python": ["python", "pandas", "scikit-learn", "fastapi"],
        "SolidWorks": ["solidworks", "cad", "3d tasarım"],
        "Yazılım ve API Geliştirme": ["yazılım", "api", "react", "web platformu", "veritabanı"],
        "Korozyon ve Aşınma": ["korozyon", "aşınma", "paslanma", "kaplama"],
        "Malzeme Karakterizasyonu": ["karakterizasyon", "mikroyapı", "sertlik", "çekme testi"],
        "Atık Su Arıtımı": ["atık su", "atıksu", "arıtma", "koagülasyon", "kimyasal oksijen"],
        "Membran Prosesleri": ["membran", "ultrafiltrasyon", "nanofiltrasyon", "ters osmoz"],
        "Adsorpsiyon": ["adsorpsiyon", "adsorban", "aktif karbon", "biyokömür"],
        "Polimer ve Formülasyon": ["polimer", "boya", "formülasyon", "reçine", "viskozite"],
        "Güç Elektroniği": ["güç elektroniği", "invertör", "konvertör", "motor sürücü"],
        "Batarya Yönetimi": ["batarya", "bms", "hücre dengeleme", "termal yönetim"],
        "Enerji Verimliliği": ["enerji tüketimi", "enerji verimliliği", "tasarruf", "yük profili"],
        "Üretim Planlama": ["üretim planlama", "çizelgeleme", "hat dengeleme", "kapasite"],
        "Tedarik Zinciri": ["tedarik", "lojistik", "stok", "rota", "depo"],
        "Yaşam Döngüsü Analizi": ["lca", "yaşam döngüsü", "karbon ayak izi", "sürdürülebilirlik"],
        "Gıda Ambalajlama": ["ambalaj", "paket", "sızdırmazlık", "raf ömrü"],
        "Gıda Güvenliği": ["gıda güvenliği", "mikrobiyoloji", "hijyen", "kontaminasyon"],
    },
    "methods": {
        "Deneysel Çalışma": ["deney", "laboratuvar", "pilot", "test", "doğrulama"],
        "Veri Analizi": ["veri", "analiz", "ölçüm", "kayıt", "izleme"],
        "Makine Öğrenmesi": ["makine öğrenmesi", "yapay zeka", "tahmin modeli", "sınıflandırma"],
        "Sayısal Simülasyon": ["simülasyon", "fem", "fea", "ansys", "abaqus", "modelleme"],
        "Optimizasyon": ["optimizasyon", "en uygun", "azaltmak", "iyileştirme", "parametre"],
        "Prototip Geliştirme": ["prototip", "cihaz", "sistem geliştirmek", "sensör"],
        "Kimyasal Analiz": ["kimyasal analiz", "ph", "koi", "boi", "spektrofotometre"],
    },
    "sectors": {
        "Otomotiv": ["otomotiv", "araç", "pres hattı", "kaporta"],
        "Makine İmalatı": ["cnc", "tezgah", "makine", "imalat"],
        "Tekstil": ["tekstil", "boyama tesisi", "kumaş", "boyar madde"],
        "Kimya": ["kimya", "boya üretimi", "kimyasal", "reçine"],
        "Gıda": ["gıda", "paketleme hattı", "raf ömrü", "ambalaj"],
        "Enerji": ["enerji", "şebeke", "güneş", "rüzgar", "transformatör"],
        "Elektronik": ["elektronik", "devre", "kart", "sensör"],
        "Lojistik": ["lojistik", "depo", "rota", "tedarik"],
        "Genel Üretim": ["fabrika", "üretim hattı", "proses", "tesis"],
    },
    "project_types": {
        "Deneysel Ar-Ge": ["deney", "laboratuvar", "numune", "pilot", "doğrulama"],
        "Yazılım Geliştirme": ["yazılım", "platform", "uygulama", "api", "dashboard"],
        "Modelleme ve Simülasyon": ["model", "simülasyon", "fem", "fea", "tahmin"],
        "Saha Uygulaması": ["saha", "hat üzerinde", "fabrikada", "gerçek zamanlı"],
        "Süreç İyileştirme": ["azaltmak", "iyileştirme", "verim", "optimizasyon", "maliyet"],
    },
}

